package fr.ece.pfe_project.widget;

import fr.ece.pfe_project.model.CarnetAdresses;
import javax.swing.JOptionPane;
import fr.ece.pfe_project.database.DatabaseHelper;
import static fr.ece.pfe_project.database.DatabaseHelper.carnetAdresseExists;
import fr.ece.pfe_project.panel.ListPanel;

/**
 *
 * @author Presentation
 */
public class CarnetAdressesDialog extends javax.swing.JDialog {
    
    private CarnetAdresses ca;
    /**
     * Creates new form CarnetAdressesDialog
     */
    public CarnetAdressesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
    public CarnetAdresses getCa(){
        return ca;
    }
    
    public void setCa(CarnetAdresses ca){
        this.ca = ca;
        this.nomCompagnieButton.setText(ca.getCompagnieca());
        this.nbGuichet.setValue(ca.getNombreGuichet());
        this.societeAssistance.setText(ca.getSocieteAssistance());
        this.telephone.setText(ca.getTelephone());
    }
    
    public static boolean verifierInt(String entier) {
        boolean v = false;
        try {
            //split du numero
            String[] num = entier.split(" ");
            for(int i=0; i<num.length;i++){
                //on essaie de convertir la chaîne en nombre entier
            Integer.parseInt(num[i]);
            }
            //conversion aboutie, v prend la valeur true
            v = true;
            } catch (Exception e) {
            //conversion échouée, levée d'une exception, v prend false
            v = false;
        }
        //on retourne v
        return v;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomCompagnieButton = new javax.swing.JTextField();
        societeAssistance = new javax.swing.JTextField();
        validateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nbGuichet = new javax.swing.JSpinner();
        telephone = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nom de la compagnie : ");

        jLabel2.setText("Nombre minimum de guichets : ");

        jLabel3.setText("Société d'assistance : ");

        jLabel4.setText("Téléphone : ");

        validateButton.setText("OK");
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nbGuichet.setModel(new javax.swing.SpinnerNumberModel(1, 0, 50, 1));

        try {
            telephone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(validateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomCompagnieButton)
                                    .addComponent(societeAssistance)
                                    .addComponent(nbGuichet, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(telephone))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomCompagnieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(societeAssistance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(telephone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbGuichet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(validateButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.nomCompagnieButton.setText("");
        this.nbGuichet.setValue(1);
        this.societeAssistance.setText("");
        this.telephone.setText("");
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        try {
            String compagnieCa = this.nomCompagnieButton.getText();
            String societeAssistance = this.societeAssistance.getText();
            String telephone = this.telephone.getText();
            Integer nbGuichets = (Integer)this.nbGuichet.getValue();
            //Vérification dans la base pour attribuer un id unique
            
            //Vérification du téléphone
            if(verifierInt(telephone) == false){
                JOptionPane.showMessageDialog(this, "Le numéro de téléphone ne doit contenir que des caractères numériques", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            }
            else if(verifierInt(telephone) == true && telephone.length() != 10){
                System.out.println("Taille : " + telephone.length());
                JOptionPane.showMessageDialog(this, "Le numéro de téléphone est incorrecte", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                ca = new CarnetAdresses();
                ca.setCompagnieca(compagnieCa);
                ca.setSocieteAssistance(societeAssistance);
                ca.setTelephone(telephone);
                ca.setNombreGuichet(nbGuichets);
                //Enregistrement dans la bdd
                if(carnetAdresseExists(ca) == false){
                    DatabaseHelper.addCarnetAdresses(ca);
                }
                else{
                    ca = null;
                    JOptionPane.showMessageDialog(this, "L'élément que vous voulez enregistrer existe déjà en base de donnée", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                }
                this.dispose();
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur de saisie", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_validateButtonActionPerformed

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner nbGuichet;
    private javax.swing.JTextField nomCompagnieButton;
    private javax.swing.JTextField societeAssistance;
    private javax.swing.JFormattedTextField telephone;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables
}
