/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ece.pfe_project.panel;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JToggleButton;
import fr.ece.pfe_project.panel.MainPanel.ToolbarsListener;

/**
 *
 * @author pierreghazal
 */
public class ToolbarEntityPanel extends javax.swing.JPanel implements ActionListener {

    public enum ENTITY {

        NONE, CAMERA, EXCELROW, LISTINGVOLS, CARNETADRESSE
    }

    public interface ToolbarEntityListener {

        public void entityHasChange(ENTITY typeEntity);
    }

    private final ToolbarsListener toolbarsListener;

    /**
     * Creates new form ToolbarEntity
     *
     * @param listener
     */
    public ToolbarEntityPanel(ToolbarsListener listener) {
        initComponents();

        this.toolbarsListener = listener;

        this.cameraButton.addActionListener(this);
        this.cameraButton.setActionCommand(ENTITY.CAMERA.toString());
        this.excelButton.addActionListener(this);
        this.excelButton.setActionCommand(ENTITY.EXCELROW.toString());
        this.listingVols.addActionListener(this);
        this.listingVols.setActionCommand(ENTITY.LISTINGVOLS.toString());
        this.carnetAdressesButton.addActionListener(this);
        this.carnetAdressesButton.setActionCommand(ENTITY.CARNETADRESSE.toString());
    }

    @Override
    public void actionPerformed(ActionEvent e) {

        if (ENTITY.CAMERA.toString().equals(e.getActionCommand())) {

            if (!cameraButton.isSelected()) {
                this.cameraButton.setSelected(false);
                this.toolbarsListener.entityHasChange(ENTITY.NONE);
            } else {
                this.cameraButton.setSelected(true);
                this.excelButton.setSelected(false);
                this.listingVols.setSelected(false);
                this.carnetAdressesButton.setSelected(false);
                this.toolbarsListener.entityHasChange(ENTITY.CAMERA);
            }
               
        } else if (ENTITY.EXCELROW.toString().equals(e.getActionCommand())) {

            if (!excelButton.isSelected()) {
                this.excelButton.setSelected(false);
                this.toolbarsListener.entityHasChange(ENTITY.NONE);
            } else {
                this.cameraButton.setSelected(false);
                this.excelButton.setSelected(true);
                this.carnetAdressesButton.setSelected(false);
                this.listingVols.setSelected(false);
                this.toolbarsListener.entityHasChange(ENTITY.EXCELROW);
            }
            
            
        } else if (ENTITY.LISTINGVOLS.toString().equals(e.getActionCommand())) {

            if (!listingVols.isSelected()) {
                this.listingVols.setSelected(false);
                this.toolbarsListener.entityHasChange(ENTITY.NONE);
            } else {
                this.cameraButton.setSelected(false);
                this.excelButton.setSelected(false);
                this.carnetAdressesButton.setSelected(false);
                this.listingVols.setSelected(true);
                this.toolbarsListener.entityHasChange(ENTITY.LISTINGVOLS);
            }

        } else if (ENTITY.CARNETADRESSE.toString().equals(e.getActionCommand())) {

            if (!carnetAdressesButton.isSelected()) {
                this.carnetAdressesButton.setSelected(false);
                this.toolbarsListener.entityHasChange(ENTITY.NONE);
            } else {
                this.cameraButton.setSelected(false);
                this.excelButton.setSelected(false);
                this.listingVols.setSelected(false);
                this.carnetAdressesButton.setSelected(true);
                this.toolbarsListener.entityHasChange(ENTITY.CARNETADRESSE);
            }

        }
    }

    public void resetToggleButtons() {

        this.toolbarsListener.entityHasChange(ENTITY.NONE);

        // Unselect every JToggleButton in the Container
        for (Component button : this.getComponents()) {
            if (button instanceof JToggleButton) {
                ((JToggleButton) button).setSelected(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cameraButton = new javax.swing.JToggleButton();
        excelButton = new javax.swing.JToggleButton();
        listingVols = new javax.swing.JToggleButton();
        carnetAdressesButton = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(90, 32767));
        setPreferredSize(new java.awt.Dimension(90, 600));

        cameraButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdatepicker/icons/video.png"))); // NOI18N

        excelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdatepicker/icons/excel.png"))); // NOI18N
        excelButton.setMaximumSize(new java.awt.Dimension(104, 29));
        excelButton.setMinimumSize(new java.awt.Dimension(104, 29));
        excelButton.setPreferredSize(new java.awt.Dimension(104, 29));

        listingVols.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdatepicker/icons/plane.png"))); // NOI18N

        carnetAdressesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdatepicker/icons/directory.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cameraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listingVols, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carnetAdressesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cameraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listingVols, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carnetAdressesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cameraButton;
    private javax.swing.JToggleButton carnetAdressesButton;
    private javax.swing.JToggleButton excelButton;
    private javax.swing.JToggleButton listingVols;
    // End of variables declaration//GEN-END:variables
}
